import type { TVShow } from './types';

export const tvShows: TVShow[] = [
  {
    id: 1,
    title: 'Chronos',
    slug: 'chronos',
    year: 2023,
    rating: 8.8,
    seasons: 2,
    genre: ['Sci-Fi', 'Drama', 'Thriller'],
    synopsis: 'A secret organization develops time travel technology, but its use creates unforeseen paradoxes that threaten the fabric of reality.',
    posterUrl: 'https://placehold.co/400x600.png',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    cast: [
      { name: 'Rebecca Ferguson', role: 'Dr. Evelyn Reed' },
      { name: 'Mahershala Ali', role: 'Director Thorne' },
    ],
    director: 'Alex Garland',
  },
  {
    id: 2,
    title: 'The Gilded Cage',
    slug: 'the-gilded-cage',
    year: 2022,
    rating: 9.1,
    seasons: 3,
    genre: ['Period Drama', 'History'],
    synopsis: 'Set in 19th-century New York, this series follows the dramatic lives and rivalries of the city\'s most powerful and wealthy families.',
    posterUrl: 'https://placehold.co/400x600.png',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    cast: [
      { name: 'Carrie Coon', role: 'Bertha Russell' },
      { name: 'Morgan Spector', role: 'George Russell' },
    ],
    director: 'Julian Fellowes',
  },
  {
    id: 3,
    title: 'Northwood',
    slug: 'northwood',
    year: 2024,
    rating: 8.2,
    seasons: 1,
    genre: ['Crime', 'Mystery'],
    synopsis: 'In a small, isolated town in the Pacific Northwest, a series of disappearances forces a reclusive sheriff to confront the town\'s dark secrets.',
    posterUrl: 'https://placehold.co/400x600.png',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    cast: [
      { name: 'Joel Kinnaman', role: 'Sheriff Brody' },
      { name: 'Kaitlyn Dever', role: 'Deputy Miller' },
    ],
    director: 'Cary Joji Fukunaga',
  },
];
